In [2]:
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.utils import to_categorical

# 1. Récupérez le dataset CIFAR-10
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()


170498071/170498071 [==============================] - 75s 0us/step


In [4]:

# 2. Explorez le dataset
print("Taille du dataset d'entraînement :", x_train.shape)
print("Taille du dataset de test :", x_test.shape)
print("Nombre d'images d'entraînement :", len(x_train))
print("Nombre d'images de test :", len(x_test))
num_classes = len(set(y_train.flatten()))
print("Nombre de classes :", num_classes)

# Afficher les 10 premières étiquettes d'entraînement
print("Labels d'entraînement :", y_train[:10])

# 3. Prétraitez les données
# Normalisation des images (mise à l'échelle des valeurs entre 0 et 1)
x_train = x_train / 255.0
x_test = x_test / 255.0

# One-hot encoding des étiquettes
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

# 4. Construisez un réseau de neurones dense
model = models.Sequential()

# Ajoutez une couche d'aplatissement pour convertir les images en vecteurs
model.add(layers.Flatten(input_shape=(32, 32, 3)))

# Ajoutez une couche dense avec 128 neurones et une fonction d'activation ReLU
model.add(layers.Dense(128, activation='relu'))

# Ajoutez une couche de sortie avec le nombre de neurones égal au nombre de classes
model.add(layers.Dense(num_classes, activation='softmax'))

# Affichez un résumé du modèle
model.summary()

Taille du dataset d'entraînement : (50000, 32, 32, 3)
Taille du dataset de test : (10000, 32, 32, 3)
Nombre d'images d'entraînement : 50000
Nombre d'images de test : 10000
Nombre de classes : 2
Labels d'entraînement : [[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 3072)              0         
                                                                 
 dense_2 (Dense)             (None, 128)               393344    
                                                                 
 dense_3 (Dense)             (Non